[project]
name = "avouch"
version = "0.1.0"
description = "An agentic red-teaming and evaluation framework for LLM safety"
authors = [
    {name = "Swapnil Anil Kale",email = "swapnil2304@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq (>=1.2.0,<2.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]

[tool.poetry]
packages = [{include = "avouch", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
